AddModelVirtualAttributeCheck: { }
# AlwaysAddDbIndexCheck: { }
# CheckSaveReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
# HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
NotUseTimeAgoInWordsCheck: { ignored_files: ['app/views/account_expire_notification/account_expire_notification.text.haml'] }
SimplifyRenderInViewsCheck: {
  ignored_files: [
    'app/views/certificates/index.html.haml' # because we want to render webservices in an certificate view
  ]
}
# UseQueryAttributeCheck: { }
# LawOfDemeterCheck: { }
# LongLineCheck: { max_line_length: 80 }

# MoveCodeIntoControllerCheck: { }
# MoveCodeIntoHelperCheck: { array_count: 3 }
# MoveCodeIntoModelCheck: { use_count: 2 }
# MoveFinderToNamedScopeCheck: { }
# MoveModelLogicIntoModelCheck: { use_count: 4 }
# NeedlessDeepNestingCheck: { nested_count: 2 }
# NotRescueExceptionCheck: { }
# NotUseDefaultRouteCheck: { }
# OveruseRouteCustomizationsCheck: { customize_count: 3 }
# ProtectMassAssignmentCheck: { }
# RemoveEmptyHelpersCheck: { }
# # # RemoveTabCheck: { }
# RemoveTrailingWhitespaceCheck: { }
# RemoveUnusedMethodsInControllersCheck: { except_methods: [] }
# RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
# RemoveUnusedMethodsInModelsCheck: { except_methods: [] }
# ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
# ReplaceInstanceVariableWithLocalVariableCheck: { }
# RestrictAutoGeneratedRoutesCheck: { }
# SimplifyRenderInControllersCheck: { }
# # # UseBeforeFilterCheck: { customize_count: 2 }
# UseModelAssociationCheck: { }
# UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
# # # UseParenthesesInMethodDefCheck: { }
# UseObserverCheck: { }
# UseSayWithTimeInMigrationsCheck: { }
# UseScopeAccessCheck: { }
# UseTurboSprocketsRails3Check: { }
