production:
  url: redis://<%= ENV['REDIS_SENTINEL_NAME'] %>:6379/0
  password: "<%=Vault.logical.read('secret/application').data[:'redis.password']%>"
  role: master
  sentinels:
    - host: "<%=ENV['REDIS_SENTINEL_HOST']%>"
      port: "26379"

